name: Static Analysis

on:
  pull_request:
  push:

jobs:
  tests:
    name: Static Analysis for PHP

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip ci') && !github.event.pull_request.draft"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - uses: ramsey/composer-install@v2

      - name: Psalm
        run: vendor/bin/psalm